### ISSUE TITLE
Error code 10486 not returning to PayPal

### ISSUE THREAD

**Issue by Sheloma** [nopSolutions/paypalexpress-plugin-for-nopcommerce#10]
when user selects a different address on PayPal then what he selected in checkout on website, or if card gets declined, PayPal will issue a 10486 Error and we need to reroute the customer back to his paypal account where he can see exactly what went wrong and fix, as of now it doesnt reroute the customer back to paypal.

https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/

this is the error that we get from PayPal
Error while placing order. Error 1: Payment error: LongMessage: This transaction couldn't be completed. Please redirect your customer to PayPal. ShortMessage: This transaction couldn't be completed. ErrorCode: 10486 . Error 2: Payment error: .

**Comment by skoshelev** [comment]
This plugin is supported as is, for those clients who for some reason do not want or cannot upgrade to a newer integration. There are no plans to make changes to functionality.

Closed #10
