### ISSUE TITLE
PayPal Express Plugin problem

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#11]
I have admin area > configuration > settings > shipping settings configured and all warehouses have address setup. Yet, I am seeing the following error when I try to use Express checkout. I can checkout just fine with all other payment methods.

"An error occurred setting up your cart for PayPal."

I find the following error messages in the Log:
SetExpressCheckoutResponseType returned - Part 1 of 1
Error passing cart to PayPal
Shipping (USPS (US Postal Service)). Shipping address is not set
Shipping (FedEx). Shipping address is not set

Originally posted at https://github.com/nopSolutions/nopCommerce/issues/2765

**Comment by skoshelev** [comment]
Can't reproduce on the latest version of nopCommerce

Closed #11
