### ISSUE TITLE
Bug when using currency other than primary currency

### ISSUE THREAD

**Issue by darrenmccarra** [nopSolutions/paypalexpress-plugin-for-nopcommerce#13]
When checking out using any currency other than the primary currency, the primary currency value is sent to PayPal with the currency that the user checked out in. So the user can checkout in GBP for example (with EUR the base currency). The EUR value is sent to PayPal but the currency sent is GBP.

For example, one product might cost €1.00 or £0.88. If I checkout in GBP £1.00GBP is sent to PayPal instead of £0.88GBP. This bug renders the plugin unusable on multi-currency website.

Bug exists on nopCommerce 3.5 (may exist on other versions too).

**Comment by skoshelev** [comment]
Closed #13

**Comment by mk148a** [comment]
It's not fixed dear friends, its still in nopcommerce 4.20+
https://github.com/nopSolutions/paypalexpress-plugin-for-nopcommerce/issues/21

**Comment by SobhaneSobhane** [comment]
It's still in nopcommerce 4.20
not fixed

**Comment by skoshelev** [comment]
Can't reproduce

Closed #13
