### ISSUE TITLE
Empty Cart with Chrome

### ISSUE THREAD

**Issue by justinhof** [nopSolutions/paypalexpress-plugin-for-nopcommerce#14]
If using Chrome, unless the customer is signed in, when the customer returns to the checkout confirm page, the shopping cart is empty and customer cannot complete purchase.

Using IE and Microsoft Edge, and no issue. Just in Chrome does this behavior occur. Only when customer has not logged into storefront as well.

**Comment by skoshelev** [comment]
Can't reproduce

Closed #14
