### ISSUE TITLE
Object Reference Not Set Error When Product Attribute is Present

### ISSUE THREAD

**Issue by wsypooh** [nopSolutions/paypalexpress-plugin-for-nopcommerce#15]
PaypalExpressCheckout .RequiresShipping() method calls (there are 3 in the project) should pass .RequiresShipping(_productService, _productAttributeParser) from nopcommerce 4.0 instead of passing nothing.

If nothing is passed, an object reference exception is called in ShoppingCartItemExtensions.IsShipEnabled because it does not check _productService if null but uses it. This happens if a product has attributes. This error happens after logging in Paypal and continuing to pay to redirect it back to the website to confirm.

This bug happens in the CheckMoneyOrder Plugin as well as it calls the same method without passing anything.

**Comment by skoshelev** [comment]
Can't reproduce on nopCommerce 4.10

Closed #15
