### ISSUE TITLE
Remove deprecated values from the DoCapture API calls

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#17]
Later this month, we will be deprecating three values from the DoCapture API calls. These three values will no longer be returned in the API response:

TAXAMT
TRANSACTIONTYPE
RECEIPTID

Could you please look into your logic for the Express Checkout module to determine if you are doing anything with these values from the DoCapture response? If so, let’s sync up to discuss action plan.

For details, see the NVP 9https://developer.paypal.com/docs/classic/api/merchant/DoCapture_API_Operation_NVP/) and SOAP (https://developer.paypal.com/docs/classic/api/merchant/DoCapture_API_Operation_SOAP/) documentation.

**Comment by skoshelev** [comment]
We do not use obsolete values from ​​the DoCapture API calls

Closed #17
