### ISSUE TITLE
error

### ISSUE THREAD

**Issue by marcelowu** [nopSolutions/paypalexpress-plugin-for-nopcommerce#18]
error ubuntu 19.04

**Comment by skoshelev** [comment]
Hi @marcelowu. Could you please add more details, which error do you get?

**Comment by marcelowu** [comment]
![2019-08-15 22-59-03屏幕截图](https://user-images.githubusercontent.com/30912144/63138493-260ccb00-bfb1-11e9-82c3-d202f688d071.png)
![2019-08-15 22-59-26屏幕截图](https://user-images.githubusercontent.com/30912144/63138494-260ccb00-bfb1-11e9-9275-3d39c5f0d9dc.png)
