### ISSUE TITLE
Can i use it for develop branc?

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/paypalexpress-plugin-for-nopcommerce#20]
https://github.com/nopSolutions/nopCommerce/commit/09c24aebfdcd8f0fe28eda8f85d90eb676601d40
Can i use that plugin with 4.30 develop branch?

**Comment by AndreiMaz** [comment]
We plan to upgrade this plugin to support 4.30 only after the official release of nopCommerce 4.30 (still under development)
