### ISSUE TITLE
Currency Conversion Error

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/paypalexpress-plugin-for-nopcommerce#21]
Hi there, 
My shop current Currency is GBP. All product prices put with gbp, but when i use paypal sandbox i have problem. For example my item price 270gbp, when i change my shop curreny to usd its changed via 353usd but when i order via paypal express its reduced to 270usd. 

And if i order with still in GBP currecy, paypal express is reduced to 206usd.

So PayPal express plugin always exchange price usd->gbp, but finall currecy is usd.
CAn you help me please?

**Comment by mk148a** [comment]
Update: I had "Is primary exchange rate currency ->USD, Is primary store currency->GBP".
Now I am updating that to this: "Is primary exchange rate currency ->GBP,Is primary store currency->GBP." 
But I now have a different problem. When I buy via gbp its work perfectly, but when I buy via USD I got that error:
"Error passing cart to PayPal"
"10413: The totals of the cart item amounts do not match order amounts."

whats wrong?

**Comment by exileDev** [comment]
Can't reproduce. 
Closed #21
