### ISSUE TITLE
GetUnitPrice and Product attribute is not found

### ISSUE THREAD

**Issue by mk148a** [nopSolutions/paypalexpress-plugin-for-nopcommerce#22]
Hi there your plugin is not work because this commit is changed IPriceCalculationService.cs and 
Libraries\Nop.Core\Domain\Orders\ShoppingCartItem.cs is changed:
https://github.com/nopSolutions/nopCommerce/commit/f021d40d4f8fe2a08e53e00beadfb67f17feb000#diff-e8597244943333e21392f60732ef172aL72

please fix it with latest commit on original nopCommerce.

Best Regards

**Comment by exileDev** [comment]
Fixed in the `nopCommerce-4.30` branch.
