### ISSUE TITLE
JS error allows multiple orders

### ISSUE THREAD

**Issue by gkennedy1** [nopSolutions/paypalexpress-plugin-for-nopcommerce#26]
The following line needs to be updated to <script asp-location="Footer"> to fix the disabling of the confirmation button on submit.

https://github.com/nopSolutions/paypalexpress-plugin-for-nopcommerce/blob/177450aa65a327edb4b0ae75fa908647ec8fade8/Nop.Plugin.Payments.PayPalExpressCheckout/Views/Confirm.cshtml#L16

This client side issue also highlights an issue with the PayPalExpressCheckoutService IsMinimumOrderPlacementIntervalValidAsync method that should be checking for duplicate orders. When debugging locally I can see that the SearchOrdersAsync is not returning the first order during the PlaceOrder for the second order. I can't work out why, maybe caching or async has stopped it working as it was originally intended?

NopCommerce Version - 4.40.4
PayPalExpress plugin version - 1.36

Repro steps (before fixing the js)
1) Proceed through the PayPal Express checkout process including the PayPal sandbox.
2) When PayPal returns you to the nop checkout, go to the Confirm page
3) Click the Confirm button multiple times quickly

**Comment by skoshelev** [comment]
Closed #26
