### ISSUE TITLE
Paypal express check out plugin not working nopcommerce version 4.4

### ISSUE THREAD

**Issue by zubairanwar702** [nopSolutions/paypalexpress-plugin-for-nopcommerce#27]
I configured Paypal Express in Sandbox mode (incl. Sandbox Account) and get the following error message during checkout:
1. Log Entry:
Short: SetExpressCheckoutResponseType returned - Part 1 of 1
Full:
{"Token":null,"Timestamp":"2020-11-17T21:06:25Z","TimestampSpecified":true,"Ack":1,"CorrelationID":"6ed6591ef27b","Errors":[{"ShortMessage":"Transaction refused because of an invalid argument. See additional error messages for details.","LongMessage":"Order total is invalid.","ErrorCode":"10401","SeverityCode":1,"ErrorParameters":null},{"ShortMessage":"Transaction refused because of an invalid argument. See additional error messages for details.","LongMessage":"Item total is invalid.","ErrorCode":"10426","SeverityCode":1,"ErrorParameters":null},{"ShortMessage":"Transaction refused because of an invalid argument. See additional error messages for details.","LongMessage":"Shipping total is invalid.","ErrorCode":"10427","SeverityCode":1,"ErrorParameters":null},{"ShortMessage":"Transaction refused because of an invalid argument. See additional error messages for details.","LongMessage":"Tax total is invalid.","ErrorCode":"10429","SeverityCode":1,"ErrorParameters":null},{"ShortMessage":"Transaction refused because of an invalid argument. See additional error messages for details.","LongMessage":"Item amount is invalid.","ErrorCode":"10431","SeverityCode":1,"ErrorParameters":null}],"Version":"98.0","Build":"55058010","Any":null}

2. Log Entry:
Short: Error passing cart to PayPal
Full: 10401: Order total is invalid., 10426: Item total is invalid., 10427: Shipping total is invalid., 10429: Tax total is invalid., 10431: Item amount is invalid.

**Comment by skoshelev** [comment]
Can't reproduce this problem

Closed #27
