### ISSUE TITLE
Paypal express states that the method used in this plugin is now discontinued

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#4]
Paypal express states that the method used in this plugin is now discontinued.  https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/

https://developer.paypal.com/docs/archive/nvp-soap-api/#express-checkout

**Comment by skoshelev** [comment]
This plugin is supported as is, for those clients who for some reason do not want or cannot upgrade to a newer integration. There are no plans to make changes to functionality.

Closed #4
