### ISSUE TITLE
"Index was out of range" error

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#5]
If you have two tabs open and are logged in for both, then add to cart and go to cart.  On the second tab logout.  Now on the cart click the paypal express....... Boom chicka Boom it crashes Nopcommerce.
Short Error: (I can give you the long one if you want). "Index was ouSystem.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index"

Source: http://www.nopcommerce.com/p/1149/paypal-express-payment-plugin-nopcommerce-team.aspx (reviews)

**Comment by skoshelev** [comment]
Closed #5
