### ISSUE TITLE
Redis is not supported

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#6]
Paypal express will not work correctly on a Cluster Server with Redis.  It crashes Nopcommerce when trying to confirm order.
Short Error: (I can give you the long one if you want). "Type 'System.Xml.XmlElement' in Assembly 'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable."

Source: http://www.nopcommerce.com/p/1149/paypal-express-payment-plugin-nopcommerce-team.aspx (reviews)

**Comment by sefacan** [comment]
Hi Andrei,
I have the same problem.
With NewtonSoft, I solved it by serializing class to Json object.

**Comment by sefacan** [comment]
Hi @AndreiMaz,
This is an important issue. I can't find a solution.

**Comment by skoshelev** [comment]
Can't reproduce on the nopCommerce 4.20

Closed #6
