### ISSUE TITLE
Anonymous checkout allowed” and “Require registration for downloadable products” issue

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/paypalexpress-plugin-for-nopcommerce#7]
If “Anonymous checkout allowed” is checked on AND “Require registration for downloadable products” is checked on and you add a downloadable product to the cart you can check out anonymously with Paypl Exress

Source: http://www.nopcommerce.com/p/1149/paypal-express-payment-plugin-nopcommerce-team.aspx (reviews)

**Comment by skoshelev** [comment]
Closed #7
